-- Optional PostgreSQL/Supabase schema for STORAGE_MODE=supabase.
-- The default STORAGE_MODE=memory does not require a database.

create table if not exists audit_batches (
  batch_id text primary key,
  status text not null default 'OPEN',
  merkle_root text,
  item_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists audit_events (
  event_id text primary key,
  event_type text not null,
  actor_id text not null default 'anonymous',
  related_job_id text,
  related_resource_hash text,
  batch_id text references audit_batches(batch_id),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  job_id text,
  content_digest text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_events_job on audit_events(related_job_id);
create index if not exists idx_audit_events_resource on audit_events(related_resource_hash);
create index if not exists idx_audit_events_batch on audit_events(batch_id);
